# Generated by Django 5.1.7 on 2025-04-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolarPanels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ady')),
                ('power', models.FloatField(default=100.0, verbose_name='Kuwwaty')),
                ('price', models.FloatField(default=0.0, verbose_name='Bahasy')),
            ],
            options={
                'verbose_name': 'Gün paneli',
                'verbose_name_plural': 'Gün panelleri',
            },
        ),
    ]
