# Generated by Django 5.1.7 on 2025-04-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvertorsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TOR', 'Tor Inverter'), ('GIBRID', 'Gibrid Inverter')], help_text='Type of inverter', max_length=10)),
                ('name', models.CharField(max_length=255, verbose_name='Ady')),
                ('power', models.FloatField(default=100.0, verbose_name='Kuwwaty')),
                ('price', models.FloatField(default=0.0, verbose_name='Bahasy')),
            ],
            options={
                'verbose_name': 'Gün paneli',
                'verbose_name_plural': 'Gün panelleri',
            },
        ),
    ]
